### ISSUE TITLE
Has error in my system [ubuuntu 22.04]

### ISSUE THREAD

**Issue by mst-ghi** [farhadeidi/create-mantine#1]
$$ npx create-mantine my-mantine

yarn create v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-vite@3.2.1" with binaries:
      - create-vite
      - cva
error Cannot create "/usr/local/bin/create-next-app" due to insufficient permissions.
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
node:internal/errors:841
  const err = new Error(message);
              ^

Error: Command failed: yarn create vite my-mantine --template react-ts
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at runCommand (file:///home/mostafa/.npm/_npx/d4422f28cf7060e7/node_modules/create-mantine/bin/index.js:936:56)
    at createReactViteApp (file:///home/mostafa/.npm/_npx/d4422f28cf7060e7/node_modules/create-mantine/bin/index.js:1067:11)
    at build (file:///home/mostafa/.npm/_npx/d4422f28cf7060e7/node_modules/create-mantine/bin/index.js:1091:11)
    at file:///home/mostafa/.npm/_npx/d4422f28cf7060e7/node_modules/create-mantine/bin/index.js:1093:1
    at file:///home/mostafa/.npm/_npx/d4422f28cf7060e7/node_modules/create-mantine/bin/index.js:1095:3
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 40678,
  stdout: null,
  stderr: null
}

**Comment by mst-ghi** [comment]
fixed
